version: '3.8'
services:
  nextjs-app:
    build: 
      .context: .
      dockerfile: dockerfile
  db:
    image: postgres:15-alpine
    container_name: todo_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678@Liam
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: